# 3. Load fundamental ratios for the ML value factor (Refinitiv, point-in-time)

The ML value factor scores stocks from **18 fundamental ratios** (`RATIO_COLUMNS` – P/E, P/B, EV/EBIT, RoE,
Debt/Equity, ...). This notebook pulls the raw accounting items from Refinitiv for a universe, derives the ratios
with one shared formula set (`data_engineering.fundamentals.ratios.compute_ratios`) and stores them in
`dbo.security_fundamentals`, one row per (security, ratio, fiscal period end).

Why store history rather than a snapshot? Because a backtest must only use what was **known at the time**.
`StaticFundamentalsProvider` serves the latest row per security with `effective_date <= as_of_date`, so a
2021 rebalance can never see a 2024 filing. `effective_date` is the fiscal **period end**; statements are published
weeks later, which is why the scoring side adds an `availability_lag_days` (notebook 04).

| Step | Library call |
|---|---|
| Resolve the universe | `data_engineering.loaders.portfolios.portfolio_member_ids` |
| Pull quarterly ratio history and upsert it, retrying missed names individually | `data_engineering.loaders.load_fundamentals_with_retry` |
| Coverage of what landed | `data_engineering.loaders.fundamentals_coverage` |
| Prove there is no look-ahead | `data_engineering.loaders.check_point_in_time` |

Re-running for the same window is safe: writes are a non-destructive MERGE.

## 3.1 Parameters

In [3]:
UNIVERSE = "SP500"          # portfolio whose members to load
FROM_DATE = "2020-01-01"    # first fiscal period end to keep
TO_DATE = "2026-08-31"      # history end / snapshot date
FREQUENCY = "Q"             # "Q" quarterly history (recommended) | "FY" single latest annual snapshot
WRITE_DB = True             # False: pull a sample and inspect only
SAMPLE_LIMIT = None         # e.g. 20 for a smoke test; None = whole universe
SOURCE_VENDOR = "refinitiv"

## 3.2 Connections and universe

In [4]:
import sys
import os

import pandas as pd

# Get the current notebook's directory and go up to parent
current_dir = os.getcwd()
parent_dir = os.path.dirname(os.path.dirname(current_dir))

if parent_dir not in sys.path:
    sys.path.append(parent_dir)

print(f"Current directory: {current_dir}")
print(f"Added to path: {parent_dir}")
data_eng_path = os.path.join(parent_dir, 'data_engineering')
files_path = os.path.join(parent_dir, 'toolkit\\files')
print(f"Data engineering folder exists: {os.path.exists(data_eng_path)}")
print(f"Files folder exists: {os.path.exists(files_path)}")

Current directory: c:\SourceCode\InvestmentManagement\toolkit\notebooks
Added to path: c:\SourceCode\InvestmentManagement
Data engineering folder exists: True
Files folder exists: True

In [5]:
import logging

import pandas as pd

from data_engineering.database import database
from data_engineering.fundamentals import RATIO_COLUMNS, RefinitivFundamentalsProvider, StaticFundamentalsProvider
from data_engineering.loaders import check_point_in_time, fundamentals_coverage, load_fundamentals_with_retry
from data_engineering.loaders.portfolios import portfolio_member_ids
from data_engineering.refinitiv import ensure_session

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
ensure_session()
engine, connection, conn_str, session = database.get_db_connection()

members = portfolio_member_ids(engine, UNIVERSE)
master = database.read_security_master(session, engine)
universe = master[master["security_id"].isin(members)][["security_id", "name"]].rename(columns={"name": "symbol"}).drop_duplicates("security_id")
if SAMPLE_LIMIT:
    universe = universe.head(SAMPLE_LIMIT)
print(f"{len(universe)} securities in universe '{UNIVERSE}'")
universe.head()

2026-09-25 19:03:20,750 INFO httpx: HTTP Request: GET http://localhost:9005/api/status "HTTP/1.1 200 OK"
2026-09-25 19:03:20,766 INFO httpx: HTTP Request: POST http://localhost:9005/api/handshake "HTTP/1.1 200 OK"
2026-09-25 19:03:20,767 INFO data_engineering.refinitiv.session: LSEG session opened

Database connection successful.
636 securities in universe 'SP500'

   security_id   symbol
0            1      A.N
1            2   AAL.OQ
2            3    AAP.N
3            4  AAPL.OQ
4            5   ABBV.N

## 3.3 Inspect a small sample before writing

The provider resolves each security's exchange-qualified RIC (from `security_vendor_xref`, then LSEG
`symbol_conversion`), pulls the raw items per fiscal quarter and computes the ratios. `snapshot` is the latest
quarter per security; `history` has one row per quarter.

In [6]:
sample = universe.head(5)
provider = RefinitivFundamentalsProvider(orm_session=session, orm_engine=engine, frequency=FREQUENCY, start_date=FROM_DATE)
snapshot, history = provider.get_panel_history(sample, TO_DATE, frequency=FREQUENCY, start_date=FROM_DATE)
print("snapshot:", snapshot.shape, "| history rows:", None if history is None else len(history))
if history is not None:
    print("fiscal period ends:", history["effective_date"].min().date(), "->", history["effective_date"].max().date())
snapshot.round(3)

2026-09-25 19:03:32,841 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:03:45,417 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:02,995 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:03,072 INFO data_engineering.refinitiv.client: get_history chunk 1/1 OK: 53 rows x 75 cols

snapshot: (5, 18) | history rows: 165
fiscal period ends: 2019-09-28 -> 2026-06-30

,EV/EBIT,Op. In./(NWC+FA),P/E,P/B,P/S,Op. In./Interest Expense,Working Capital Ratio,RoE,ROCE,Debt/Equity,Debt Ratio,Cash Ratio,Asset Turnover,Gross Profit Margin,(CA-CL)/TA,RE/TA,EBIT/TA,Book Equity/TL
security_id,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3.4 Load the full universe

`load_fundamentals_with_retry` runs the bulk pull, checks which securities have no rows in the window and retries
those **one at a time** (a single-RIC request rarely hits the gateway timeout that makes a whole chunk disappear).

In [7]:
if WRITE_DB:
    summary = load_fundamentals_with_retry(universe, session, engine, FROM_DATE, TO_DATE, provider_name="refinitiv", frequency=FREQUENCY, source_vendor=SOURCE_VENDOR)
    print(f"rows written: {summary['rows_written']:,} | covered: {len(summary['covered'])} | still missing: {len(summary['missing'])}")
    if summary["missing"]:
        print("missing security_ids (typically delisted / renamed):", summary["missing"][:30])
else:
    print("WRITE_DB is False - nothing written.")

2026-09-25 19:04:05,347 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:05,550 INFO data_engineering.refinitiv.client: get_history chunk 1/43 OK: 88 rows x 225 cols
2026-09-25 19:04:08,867 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:09,053 INFO data_engineering.refinitiv.client: get_history chunk 2/43 OK: 33 rows x 225 cols
2026-09-25 19:04:17,962 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:32,684 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:04:50,333 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:05:08,027 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:05:25,711 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:05:25,922 INFO data_engineering.refinitiv.client: get_history chunk 3/43 OK: 68 rows x 225 cols
2026-09-25 19:05:34,813 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:05:52,302 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:06:09,836 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:06:27,359 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:06:29,904 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:06:30,101 INFO data_engineering.refinitiv.client: get_history chunk 4/43 OK: 52 rows x 225 cols
2026-09-25 19:06:38,997 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:06:53,215 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:10,869 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:28,347 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:36,262 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:36,473 INFO data_engineering.refinitiv.client: get_history chunk 5/43 OK: 62 rows x 225 cols
2026-09-25 19:07:38,128 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:38,338 INFO data_engineering.refinitiv.client: get_history chunk 6/43 OK: 40 rows x 225 cols
2026-09-25 19:07:41,727 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:41,914 INFO data_engineering.refinitiv.client: get_history chunk 7/43 OK: 67 rows x 225 cols
2026-09-25 19:07:44,307 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:44,518 INFO data_engineering.refinitiv.client: get_history chunk 8/43 OK: 48 rows x 225 cols
2026-09-25 19:07:46,699 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:46,922 INFO data_engineering.refinitiv.client: get_history chunk 9/43 OK: 88 rows x 225 cols
2026-09-25 19:07:50,706 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:50,904 INFO data_engineering.refinitiv.client: get_history chunk 10/43 OK: 71 rows x 225 cols
2026-09-25 19:07:54,815 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:55,005 INFO data_engineering.refinitiv.client: get_history chunk 11/43 OK: 57 rows x 225 cols
2026-09-25 19:07:57,798 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:07:57,972 INFO data_engineering.refinitiv.client: get_history chunk 12/43 OK: 72 rows x 225 cols
2026-09-25 19:08:00,318 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:00,529 INFO data_engineering.refinitiv.client: get_history chunk 13/43 OK: 40 rows x 225 cols
2026-09-25 19:08:04,274 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:04,463 INFO data_engineering.refinitiv.client: get_history chunk 14/43 OK: 48 rows x 225 cols
2026-09-25 19:08:06,156 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:06,376 INFO data_engineering.refinitiv.client: get_history chunk 15/43 OK: 48 rows x 225 cols
2026-09-25 19:08:08,593 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:08,775 INFO data_engineering.refinitiv.client: get_history chunk 16/43 OK: 72 rows x 225 cols
2026-09-25 19:08:10,618 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:10,813 INFO data_engineering.refinitiv.client: get_history chunk 17/43 OK: 63 rows x 225 cols
2026-09-25 19:08:12,876 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:13,091 INFO data_engineering.refinitiv.client: get_history chunk 18/43 OK: 53 rows x 225 cols
2026-09-25 19:08:15,061 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:15,268 INFO data_engineering.refinitiv.client: get_history chunk 19/43 OK: 76 rows x 225 cols
2026-09-25 19:08:17,059 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:17,276 INFO data_engineering.refinitiv.client: get_history chunk 20/43 OK: 61 rows x 225 cols
2026-09-25 19:08:26,317 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:08:43,858 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:01,311 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:18,717 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:36,439 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:36,635 INFO data_engineering.refinitiv.client: get_history chunk 21/43 OK: 53 rows x 225 cols
2026-09-25 19:09:39,748 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:39,940 INFO data_engineering.refinitiv.client: get_history chunk 22/43 OK: 83 rows x 225 cols
2026-09-25 19:09:42,694 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:42,880 INFO data_engineering.refinitiv.client: get_history chunk 23/43 OK: 87 rows x 225 cols
2026-09-25 19:09:45,154 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:45,363 INFO data_engineering.refinitiv.client: get_history chunk 24/43 OK: 76 rows x 225 cols
2026-09-25 19:09:47,028 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:47,226 INFO data_engineering.refinitiv.client: get_history chunk 25/43 OK: 68 rows x 225 cols
2026-09-25 19:09:49,350 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:49,569 INFO data_engineering.refinitiv.client: get_history chunk 26/43 OK: 56 rows x 225 cols
2026-09-25 19:09:51,871 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:09:52,080 INFO data_engineering.refinitiv.client: get_history chunk 27/43 OK: 52 rows x 225 cols
2026-09-25 19:10:01,025 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:10:13,596 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:10:31,255 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:10:48,851 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:06,605 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:06,840 INFO data_engineering.refinitiv.client: get_history chunk 28/43 OK: 55 rows x 225 cols
2026-09-25 19:11:09,502 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:09,713 INFO data_engineering.refinitiv.client: get_history chunk 29/43 OK: 59 rows x 225 cols
2026-09-25 19:11:12,541 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:12,734 INFO data_engineering.refinitiv.client: get_history chunk 30/43 OK: 58 rows x 225 cols
2026-09-25 19:11:15,205 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:15,418 INFO data_engineering.refinitiv.client: get_history chunk 31/43 OK: 50 rows x 225 cols
2026-09-25 19:11:17,632 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:17,829 INFO data_engineering.refinitiv.client: get_history chunk 32/43 OK: 49 rows x 225 cols
2026-09-25 19:11:19,744 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:19,951 INFO data_engineering.refinitiv.client: get_history chunk 33/43 OK: 67 rows x 225 cols
2026-09-25 19:11:22,928 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:23,109 INFO data_engineering.refinitiv.client: get_history chunk 34/43 OK: 54 rows x 225 cols
2026-09-25 19:11:24,986 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:25,183 INFO data_engineering.refinitiv.client: get_history chunk 35/43 OK: 81 rows x 225 cols
2026-09-25 19:11:28,597 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:28,810 INFO data_engineering.refinitiv.client: get_history chunk 36/43 OK: 93 rows x 225 cols
2026-09-25 19:11:31,237 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:31,427 INFO data_engineering.refinitiv.client: get_history chunk 37/43 OK: 55 rows x 225 cols
2026-09-25 19:11:40,333 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:11:57,990 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:12:15,554 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:12:33,343 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:12:51,076 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:12:51,310 INFO data_engineering.refinitiv.client: get_history chunk 38/43 OK: 59 rows x 225 cols
2026-09-25 19:12:54,298 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:12:54,478 INFO data_engineering.refinitiv.client: get_history chunk 39/43 OK: 64 rows x 225 cols
2026-09-25 19:13:03,631 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:13:16,160 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:13:33,733 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:13:51,380 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:14:09,084 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:14:09,281 INFO data_engineering.refinitiv.client: get_history chunk 40/43 OK: 46 rows x 225 cols
2026-09-25 19:14:18,307 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:14:35,836 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:14:53,309 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:10,997 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:28,850 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:29,052 INFO data_engineering.refinitiv.client: get_history chunk 41/43 OK: 55 rows x 225 cols
2026-09-25 19:15:31,917 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:32,087 INFO data_engineering.refinitiv.client: get_history chunk 42/43 OK: 40 rows x 225 cols
2026-09-25 19:15:33,811 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:33,900 INFO data_engineering.refinitiv.client: get_history chunk 43/43 OK: 37 rows x 90 cols

Upserting 54992 security_fundamentals rows (non-destructive MERGE)...

2026-09-25 19:15:46,119 INFO data_engineering.fundamentals.store: wrote 54992 fundamentals rows from 'refinitiv'

Security fundamentals data successfully written (54992 rows upserted).

2026-09-25 19:15:49,407 INFO data_engineering.loaders.fundamentals_loader: coverage after initial pull: 603/636 securities
2026-09-25 19:15:52,592 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:15:52,595 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['ABMD.OQ']. -- retry in 5s
2026-09-25 19:16:00,353 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:00,355 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['ABMD.OQ']. -- retry in 5s
2026-09-25 19:16:07,892 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:07,893 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['ABMD.OQ'].
2026-09-25 19:16:07,894 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:16:07,904 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:16:08,514 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:08,516 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['AGN.N']. -- retry in 5s
2026-09-25 19:16:16,631 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:16,633 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['AGN.N']. -- retry in 5s
2026-09-25 19:16:24,298 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:24,299 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['AGN.N'].
2026-09-25 19:16:24,299 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:16:24,303 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:16:24,958 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:24,960 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['AIRC.N']. -- retry in 5s
2026-09-25 19:16:33,190 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:33,191 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['AIRC.N']. -- retry in 5s
2026-09-25 19:16:40,893 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:40,895 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['AIRC.N'].
2026-09-25 19:16:40,895 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:16:40,899 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:16:41,898 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:41,899 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['ALXN.OQ']. -- retry in 5s
2026-09-25 19:16:49,652 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:49,654 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['ALXN.OQ']. -- retry in 5s
2026-09-25 19:16:57,622 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:57,623 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['ALXN.OQ'].
2026-09-25 19:16:57,624 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:16:57,629 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:16:58,559 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:16:58,561 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['ATVI.OQ']. -- retry in 5s
2026-09-25 19:17:06,560 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:06,562 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['ATVI.OQ']. -- retry in 5s
2026-09-25 19:17:14,383 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:14,384 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['ATVI.OQ'].
2026-09-25 19:17:14,384 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:17:14,389 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:17:15,212 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:15,214 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['CERN.OQ']. -- retry in 5s
2026-09-25 19:17:22,858 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:22,861 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['CERN.OQ']. -- retry in 5s
2026-09-25 19:17:30,597 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:30,599 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['CERN.OQ'].
2026-09-25 19:17:30,600 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:17:30,604 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:17:31,476 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:31,477 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['CTXS.OQ']. -- retry in 5s
2026-09-25 19:17:39,313 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:39,315 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['CTXS.OQ']. -- retry in 5s
2026-09-25 19:17:47,098 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:47,101 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['CTXS.OQ'].
2026-09-25 19:17:47,102 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:17:47,111 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:17:47,803 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:47,805 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['CXO.N']. -- retry in 5s
2026-09-25 19:17:55,465 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:17:55,468 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['CXO.N']. -- retry in 5s
2026-09-25 19:18:03,214 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:03,216 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['CXO.N'].
2026-09-25 19:18:03,216 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:18:03,223 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:18:03,874 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:03,876 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['DFS.N']. -- retry in 5s
2026-09-25 19:18:11,712 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:11,713 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['DFS.N']. -- retry in 5s
2026-09-25 19:18:19,965 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:19,968 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['DFS.N'].
2026-09-25 19:18:19,969 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:18:19,978 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:18:20,525 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:20,527 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['DISCK.OQ']. -- retry in 5s
2026-09-25 19:18:28,718 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:28,720 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['DISCK.OQ']. -- retry in 5s
2026-09-25 19:18:36,353 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:36,355 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['DISCK.OQ'].
2026-09-25 19:18:36,356 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:18:36,361 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:18:37,288 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:37,290 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['DISH.OQ']. -- retry in 5s
2026-09-25 19:18:45,543 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:45,545 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['DISH.OQ']. -- retry in 5s
2026-09-25 19:18:53,120 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:53,122 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['DISH.OQ'].
2026-09-25 19:18:53,123 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:18:53,127 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:18:54,083 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:18:54,085 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['DRE.N']. -- retry in 5s
2026-09-25 19:19:01,686 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:01,688 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['DRE.N']. -- retry in 5s
2026-09-25 19:19:09,482 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:09,485 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['DRE.N'].
2026-09-25 19:19:09,485 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:19:09,490 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:19:10,022 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:10,023 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['ETFC.OQ']. -- retry in 5s
2026-09-25 19:19:17,519 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:17,521 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['ETFC.OQ']. -- retry in 5s
2026-09-25 19:19:25,342 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:25,344 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['ETFC.OQ'].
2026-09-25 19:19:25,346 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:19:25,352 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:19:26,146 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:26,148 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['FLIR.OQ']. -- retry in 5s
2026-09-25 19:19:33,872 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:33,874 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['FLIR.OQ']. -- retry in 5s
2026-09-25 19:19:41,530 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:41,531 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['FLIR.OQ'].
2026-09-25 19:19:41,531 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:19:41,534 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:19:42,079 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:42,081 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['FRC.N']. -- retry in 5s
2026-09-25 19:19:50,425 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:50,426 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['FRC.N']. -- retry in 5s
2026-09-25 19:19:58,451 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:58,455 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['FRC.N'].
2026-09-25 19:19:58,456 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:19:58,462 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:19:59,262 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:19:59,274 INFO data_engineering.refinitiv.client: get_history chunk 1/1 OK: 7 rows x 15 cols
2026-09-25 19:19:59,289 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:20:00,545 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:00,547 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['JWN.N']. -- retry in 5s
2026-09-25 19:20:08,408 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:08,410 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['JWN.N']. -- retry in 5s
2026-09-25 19:20:16,324 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:16,327 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['JWN.N'].
2026-09-25 19:20:16,328 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:20:16,333 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:20:17,777 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:17,778 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['KSU.N']. -- retry in 5s
2026-09-25 19:20:25,510 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:25,513 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['KSU.N']. -- retry in 5s
2026-09-25 19:20:33,204 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:33,206 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['KSU.N'].
2026-09-25 19:20:33,207 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:20:33,212 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:20:34,175 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:34,176 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 1/3 failed: LDError: Unable to resolve all requested identifiers in ['MXIM.OQ']. -- retry in 5s
2026-09-25 19:20:42,382 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:42,385 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 attempt 2/3 failed: LDError: Unable to resolve all requested identifiers in ['MXIM.OQ']. -- retry in 5s
2026-09-25 19:20:50,044 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"
2026-09-25 19:20:50,046 ERROR data_engineering.refinitiv.client: get_history chunk 1/1 FAILED after 3 attempts: Unable to resolve all requested identifiers in ['MXIM.OQ'].
2026-09-25 19:20:50,046 WARNING data_engineering.refinitiv.client: get_history chunk 1/1 returned no data (1 RICs)
2026-09-25 19:20:50,050 WARNING data_engineering.fundamentals.store: no non-null ratios to store
2026-09-25 19:20:51,088 INFO httpx: HTTP Request: POST http://localhost:9005/api/udf "HTTP/1.1 200 OK"

rows written: 54,992 | covered: 603 | still missing: 33
missing security_ids (typically delisted / renamed): [6, 20, 22, 32, 55, 105, 149, 153, 164, 171, 172, 179, 210, 238, 243, 304, 326, 343, 409, 410, 419, 449, 481, 501, 505, 511, 546, 563, 581, 606]

## 3.5 What landed

In [8]:
rows = fundamentals_coverage(session, engine, universe["security_id"].tolist(), FROM_DATE, TO_DATE, SOURCE_VENDOR)
print(f"{len(rows):,} ratio rows | {rows['security_id'].nunique()} securities | {rows['effective_date'].nunique()} distinct period ends")
per_metric = rows.groupby("metric_type")["security_id"].nunique().reindex(RATIO_COLUMNS).rename("securities_with_data")
display(per_metric.to_frame().T)
demo_metrics = ["P/E", "P/B", "EV/EBIT", "RoE"]
covered_all = rows[rows["metric_type"].isin(demo_metrics)].groupby("security_id")["metric_type"].nunique()
sec0 = covered_all[covered_all == len(demo_metrics)].index[0] if (covered_all == len(demo_metrics)).any() else universe["security_id"].iloc[0]
demo = rows[rows["security_id"] == sec0].pivot_table(index="effective_date", columns="metric_type", values="metric_value")
demo[[c for c in demo_metrics if c in demo.columns]].round(3).tail()

48,730 ratio rows | 603 securities | 233 distinct period ends

metric_type,EV/EBIT,Op. In./(NWC+FA),P/E,P/B,P/S,Op. In./Interest Expense,Working Capital Ratio,RoE,ROCE,Debt/Equity,Debt Ratio,Cash Ratio,Asset Turnover,Gross Profit Margin,(CA-CL)/TA,RE/TA,EBIT/TA,Book Equity/TL
securities_with_data,485.0,NaN,486.0,486.0,468.0,540.0,508.0,603.0,603.0,603.0,603.0,NaN,584.0,518.0,508.0,599.0,603.0,603.0

metric_type        P/E    P/B  EV/EBIT    RoE
effective_date
2021-12-31      -5.835 -1.584   -9.059  0.272
2022-12-31         NaN    NaN      NaN -0.022
2023-12-31         NaN    NaN      NaN -0.158
2024-12-31      13.548 -2.882   12.876 -0.213
2025-12-31      91.193 -2.716   24.021 -0.030

## 3.6 Point-in-time guarantee

For every quarter end in the window, ask the database provider for the panel "as of" that date and confirm that
no returned ratio has an `effective_date` later than the date asked for. The result must be **0** leaked values.

In [9]:
static = StaticFundamentalsProvider(session, engine, source_vendor=SOURCE_VENDOR)
all_rows = database.read_security_fundamentals(session, engine, metric_type=None)
all_rows = all_rows[(all_rows["source_vendor"] == SOURCE_VENDOR) & all_rows["security_id"].isin(universe["security_id"])]
worst = check_point_in_time(static, universe, FROM_DATE, TO_DATE, all_rows)
print("maximum number of future-dated ratios visible on any quarter end (must be 0):", worst)

maximum number of future-dated ratios visible on any quarter end (must be 0): 0

In [10]:
session.close()
connection.close()

**Next:** notebook **04** trains the ML value models on this history and backtests a momentum + ML-value long/short
book. The same load can be run from the command line:

```
python toolkit/scripts/load_refinitiv_fundamentals.py --universe SP500 --frequency Q --start 2020-01-01
```